name: F1 Constructors Championship Table

on:
  schedule:
  # Australian Grand Prix
    - cron: "0 6-23 15 3 *"  # Samstag 15.03.
    - cron: "0 6-23 16 3 *"  # Sonntag 16.03.
    # Chinese Grand Prix
    - cron: "0 6-23 22 3 *"
    - cron: "0 6-23 23 3 *"
    # Japanese Grand Prix
    - cron: "0 6-23 5 4 *"
    - cron: "0 6-23 6 4 *"
    # Bahrain Grand Prix
    - cron: "0 6-23 12 4 *"
    - cron: "0 6-23 13 4 *"
    # Saudi Arabian Grand Prix
    - cron: "0 6-23 19 4 *"
    - cron: "0 6-23 20 4 *"
    # Miami Grand Prix
    - cron: "0 6-23 3 5 *"
    - cron: "0 6-23 4 5 *"
    # Emilia Romagna Grand Prix
    - cron: "0 6-23 17 5 *"
    - cron: "0 6-23 18 5 *"
    # Monaco Grand Prix
    - cron: "0 6-23 24 5 *"
    - cron: "0 6-23 25 5 *"
    # Spanish Grand Prix
    - cron: "0 6-23 31 5 *"
    - cron: "0 6-23 1 6 *"
    # Canadian Grand Prix
    - cron: "0 6-23 14 6 *"
    - cron: "0 6-23 15 6 *"
    # Austrian Grand Prix
    - cron: "0 6-23 28 6 *"
    - cron: "0 6-23 29 6 *"
    # British Grand Prix
    - cron: "0 6-23 5 7 *"
    - cron: "0 6-23 6 7 *"
    # Belgian Grand Prix
    - cron: "0 6-23 26 7 *"
    - cron: "0 6-23 27 7 *"
    # Hungarian Grand Prix
    - cron: "0 6-23 2 8 *"
    - cron: "0 6-23 3 8 *"
    # Dutch Grand Prix
    - cron: "0 6-23 30 8 *"
    - cron: "0 6-23 31 8 *"
    # Italian Grand Prix
    - cron: "0 6-23 6 9 *"
    - cron: "0 6-23 7 9 *"
    # Azerbaijan Grand Prix
    - cron: "0 6-23 20 9 *"
    - cron: "0 6-23 21 9 *"
    # Singapore Grand Prix
    - cron: "0 6-23 4 10 *"
    - cron: "0 6-23 5 10 *"
    # United States Grand Prix
    - cron: "0 6-23 18 10 *"
    - cron: "0 6-23 19 10 *"
    # Mexican Grand Prix
    - cron: "0 6-23 25 10 *"
    - cron: "0 6-23 26 10 *"
    # Brazilian Grand Prix
    - cron: "0 6-23 8 11 *"
    - cron: "0 6-23 9 11 *"
    # Las Vegas Grand Prix
    - cron: "0 6-23 21 11 *"
    - cron: "0 6-23 22 11 *"
    # Qatar Grand Prix
    - cron: "0 6-23 29 11 *"
    - cron: "0 6-23 30 11 *"
    # Abu Dhabi Grand Prix
    - cron: "0 6-23 6 12 *"
    - cron: "0 6-23 7 12 *"
  workflow_dispatch:

jobs:
  update-constructors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        pip install requests
    - name: Update Constructors Championship
      env:
        NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
      run: |
        echo "🏗️ Updating Constructors Championship for..."
        python f1_constructors_table_ACTIONS.py
    - name: Log completion
      if: success()
      run: echo "✅ Constructors Championship updated at $(date)"
    - name: Log failure
      if: failure()
      run: |
        echo "❌ Drivers Championship update failed at $(date)"
        exit 1
